#ifndef LEX_TOKEN_TYPE_H
#define LEX_TOKEN_TYPE_H
typedef enum {
    _EOF = 0,
    _ID = 1,
    _INTEGER = 2,
    _STRING = 3,
    _DATA_TYPE = 4,
    _OP_PLUS = 5,
    _OP_SUBTRACT = 6,
    _OP_MULTIPLY = 7,
    _OP_DIVIDE = 8,
    _OP_MOD = 9,
    _OP_PERCENTAGE = 10,
    _USE = 11,
    _LPAREN = 12,
    _RPAREN = 13,
    _LBRACE = 14,
    _RBRACE = 15,
    _COMMA = 16,
    _RETURN = 17,
    _IF = 18,
    _ELSE = 19,
    _SEMI = 20,
    _DOT = 21,
    _AT = 22,
    _LESS_THAN = 23,
    _LARGER_THAN = 24,
    _LESS_OR_EQUALS = 25,
    _LARGER_OR_EQUALS = 26,
    _NOT_EQUALS = 27,
    _EQUALS = 28,
    _TYPE_STRING = 29,
    _TYPE_NUMBER = 30,
    _TYPE_INTEGER,
    _TYPE_FLOAT,
    _TYPE_VOID,
    _TYPE_STRUCT,
    _TYPE_COMPONENT,
    _TYPE_FUNCTION
} tokentype;
#endif
